name: SonarQube Analysis (Python)
on:
  push:
    branches:
      - main

jobs:
  sonarqubeScan1:
    name: SonarQubeScan1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: repo1/

  # sonarqube:
  #   runs-on: ubuntu-latest
  #   env:
  #     SONAR_SCANNER_VERSION: 7.1.0.4889
  #     SONAR_SCANNER_OS: linux
  #     SONAR_ARCHITECHTURE: x64
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Setup Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.8'

  #     - name: Cache SonarScanner
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.sonar/cache
  #         key: ${{ runner.os }}-sonar

  #     - name: Download SonarScanner CLI
  #       run: |
  #         curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${{ env.SONAR_SCANNER_VERSION }}-${{ env.SONAR_SCANNER_OS }}-${{ env.SONAR_ARCHITECHTURE }}.zip
  #         unzip sonar-scanner.zip

  #     - name: Run SonarScanner
  #       run: |
  #         .sonar-scanner \
  #           -Dsonar.organization=github-actions-test-sonar \
  #           -Dsonar.projectKey=Mikado1405_agenticSeek_copy \
  #           -Dsonar.sources=. \
  #           -Dsonar.host.url=https://sonarcloud.io
