name: Sonarqube

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cài đặt JDK (nếu runner chưa có sẵn Java)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Download và giải nén SonarScanner CLI (nếu chưa có trên runner)
      - name: Download SonarScanner
        run: |
          $zip = "sonar-scanner.zip"
          Invoke-WebRequest -Uri "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.0.2.4839-windows-x64.zip" -OutFile $zip
          Expand-Archive -Path $zip -DestinationPath "."
          Rename-Item -Path "sonar-scanner-cli-7.0.2.4839-windows-x64" -NewName "sonar-scanner"

      # Chạy SonarScanner trực tiếp trên Windows runner
      - name: Run SonarScanner
        shell: cmd
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner\bin\sonar-scanner.bat -D"sonar.projectKey=your_project_key" -D"sonar.sources=." -D"sonar.host.url=%SONAR_HOST_URL%" -D"sonar.login=%SONAR_TOKEN%"

